language: php

# We're only doing a code standards check; building on just 5.6 should suffice.
php:
  - 5.6

before_install:
  - cd ${TRAVIS_BUILD_DIR}

install:
  - composer install

script:
  - vendor/bin/phpcs
